name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Install Dependencies
        run: yarn

      - name: Build VuePress
        run: yarn run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "yarn-documentation"
          entrypoint: https://deno.land/std@0.131.0/http/file_server.ts
          root: docs/.vuepress/dist # Where the built HTML/CSS/JS files are located.
